# Generated by Django 4.2.1 on 2023-05-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criação', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_usuario', models.CharField(choices=[('ALUNO', 'Aluno'), ('EMPRESA', 'Empresa')], max_length=10)),
                ('curso_solicitado', models.CharField(max_length=150)),
            ],
        ),
    ]
